Use cloudinary
awesome-academy/python-naitei2024_my-wibu-list pull request #10
Opened 2024-08-16 04:30 UTC by DQB-201103

## Checklist tự review pull trước khi ready để trainer review
- [ ] Sử dụng thụt lề 2 spaces/4 spaces đồng nhất ở tất cả các files (setting lại vscode /sublime text/ ... nếu chưa cài đặt)
- [ ] Cuối mỗi file kiểm tra có end line (khi đẩy lên git xem file change không bị lỗi tròn đỏ ở cuối file)
- [ ] Mỗi dòng nếu quá dài, cần xuống dòng (maximum: 80 kí tự mỗi dòng, setting trong IDE)
- [ ] Tham khảo Python coding convention https://peps.python.org/pep-0008/
- [ ] Kiểm tra mỗi pull request chỉ 1 commit, nếu nhiều hơn 1 commit thì hãy gộp commit thành 1 rồi đẩy lại lên git
- [ ] Install [PEP8](https://pypi.org/project/pep8/) ở local để check và fix các lỗi liên quan đến syntax, coding convention. Khi gửi thì chụp ảnh PASS đính kèm trong pull
- [ ] Nếu làm việc nhóm trong project thì mỗi pull cần ít nhất 1 APPROVED từ thành viên trong nhóm

## Related Tickets
Task #79262

## WHAT (optional)
Guest - Xem những bộ anime/manga mới ra trong ngày hôm nay

## HOW
- Thể hiện ra màn hình danh sách các bộ anime/manga bắt đầu chiếu trong ngày hôm nay
- Thêm các file ảnh tương ứng cho Content
- Liên kết html để gọi đúng ảnh của Content

## WHY (optional)

## Evidence (Screenshot or Video)
<img width="1188" alt="image" src="https://github.com/user-attachments/assets/cdce0986-a2d0-489c-b64c-486bd8bb32de">
<img width="977" alt="image" src="https://github.com/user-attachments/assets/78e17c49-60d9-437d-bd73-9a1d21370273">
<img width="966" alt="image" src="https://github.com/user-attachments/assets/1ba58591-b445-4428-b00d-aa8ed297928d">
<img width="743" alt="image" src="https://github.com/user-attachments/assets/9e35e17b-ec5b-45e9-84f6-0b4847cd63a9">

## Notes (Kiến thức tìm hiểu thêm)
Cloudinary để lưu trữ hình ảnh

2024-08-16 06:16 UTC, thanhtb-0507 requested changes
(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧

2024-08-16 06:16 UTC, thanhtb-0507 commented on .editorconfig
> +# EditorConfig is awesome: https://editorconfig.org
file này có trong .gitignore nhé, kiểm tra lại và unstash nó rồi push lại nhé.

2024-08-16 06:16 UTC, thanhtb-0507 commented on .gitattributes
> +*js text eol=lf
Tương tự file này cũng có trong .gitignore nhé, thêm vào đó @DQB-201103 thiếu dòng trống cuối cùng (eof) này.

2024-08-16 06:16 UTC, thanhtb-0507 commented on wibu_catalog/admin.py
> +class OrderItemsInline(admin.TabularInline):
eh, phần order này thuộc ticket của tôi mà [79483](https://edu-redmine.sun-asterisk.vn/issues/79483) còn có cả [pull req](https://github.com/awesome-academy/python-naitei2024_my-wibu-list/pull/9) rồi cơ, nên có gì comment vô đấy giùm tôi nhé.

2024-08-16 06:16 UTC, thanhtb-0507 commented on wibu_catalog/admin.py
> +admin.site.register(Order, OrderAdmin)
Thống nhất dùng chung cái này đi
```
@admin.register(Order)
```

2024-08-16 06:16 UTC, thanhtb-0507 commented on wibu_catalog/templates/html/homepage.html
kiểm tra lại mấy file html tại thụt dòng = 2 mà hiện tại đang là 4.

2024-08-16 09:27 UTC, thanhtb-0507 approved these changes

2024-08-16 09:27 UTC, DQB-201103 commented
ready

2024-08-16 10:06 UTC, DQB-201103 commented
ready

2024-08-16 10:06 UTC, thanhtb-0507 approved these changes

2024-08-19 02:16 UTC, huongnt-2545 commented on wibu_catalog/admin.py
> +        return f"Tiêu đề: {obj.name} - Cập nhật lần cuối: {obj.lastUpdate}"
để message tiếng anh rồi I18n e nhé

2024-08-19 02:16 UTC, huongnt-2545 commented on wibu_catalog/views.py
> +    top_watching_content = Content.objects.order_by('-watching')[:5]
`5, 10, ...` -> khai báo giá trị trong file constants em nha

2024-08-19 02:16 UTC, huongnt-2545 commented on wibu_catalog/views.py
> +def product(request):
action này để hiển thị ds products phía user hở e
-> đổi lại tên action nhé `list_products`

2024-08-19 02:16 UTC, huongnt-2545 commented on wibu_catalog/views.py
> +    products = Product.objects.all()
Thêm xử lý phân trang + sắp xếp bản ghi

2024-08-19 02:21 UTC, DQB-201103 commented on wibu_catalog/views.py
> +def product(request):
phần này e không làm và chức này bạn phong sẽ làm ở pull sau ạ

2024-08-19 02:21 UTC, DQB-201103 commented on wibu_catalog/views.py
> +    products = Product.objects.all()
phần này e không làm và chức này bạn phong sẽ làm ở pull sau ạ

2024-08-19 02:40 UTC, hoanghaiphongg approved these changes

2024-08-19 02:40 UTC, DQB-201103 commented
ready

2024-08-19 02:41 UTC, huongnt-2545 approved these changes

2024-08-19 02:42 UTC, merged