Xem toàn bộ mặt hàng của shop
awesome-academy/python-naitei2024_my-wibu-list pull request #13
Opened 2024-08-16 07:32 UTC by hoanghaiphongg

## Checklist tự review pull trước khi ready để trainer review
- [ ] Sử dụng thụt lề 2 spaces/4 spaces đồng nhất ở tất cả các files (setting lại vscode /sublime text/ ... nếu chưa cài đặt)
- [ ] Cuối mỗi file kiểm tra có end line (khi đẩy lên git xem file change không bị lỗi tròn đỏ ở cuối file)
- [ ] Mỗi dòng nếu quá dài, cần xuống dòng (maximum: 80 kí tự mỗi dòng, setting trong IDE)
- [ ] Tham khảo Python coding convention https://peps.python.org/pep-0008/
- [ ] Kiểm tra mỗi pull request chỉ 1 commit, nếu nhiều hơn 1 commit thì hãy gộp commit thành 1 rồi đẩy lại lên git
- [ ] Install [PEP8](https://pypi.org/project/pep8/) ở local để check và fix các lỗi liên quan đến syntax, coding convention. Khi gửi thì chụp ảnh PASS đính kèm trong pull
- [ ] Nếu làm việc nhóm trong project thì mỗi pull cần ít nhất 1 APPROVED từ thành viên trong nhóm

## Related Tickets
- ticket #79488

## WHAT (optional)
- Change number items `completed/total` in admin page.

## HOW
- I edit js file, inject not_vary_normal items in calculate function.

## WHY (optional)
- Because in previous version - number just depends on `normal` items. But in new version, we have `state` and `confirm_state` depends on both `normal` + `not_normal` items.

## Evidence (Screenshot or Video)
![Ảnh chụp màn hình 2024-08-16 143212](https://github.com/user-attachments/assets/04e6c037-ab45-4b8f-979f-3fdf383d2874)

## Notes (Kiến thức tìm hiểu thêm)

2024-08-16 07:32 UTC, hoanghaiphongg commented
Ready

2024-08-16 07:38 UTC, thanhtb-0507 requested changes

2024-08-16 07:38 UTC, thanhtb-0507 commented on wibu_catalog/templates/html/warehouse.html
> +    <meta charset="UTF-8">
thay 4 space thành 2 space thôi nhé

2024-08-16 07:43 UTC, DQB-201103 commented on wibu_catalog/templates/html/homepage.html
> +                <li><a href="#">{% trans "CATEGORIES" %}</a></li>
Trang chủ thì thành Home chứ nhỉ hay tên web cũng được

2024-08-16 07:43 UTC, DQB-201103 commented on wibu_catalog/templates/html/homepage.html
>          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
hình như phải tải về đặt trong static

2024-08-16 07:43 UTC, DQB-201103 commented on wibu_catalog/templates/html/homepage.html
>          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
đoạn là code nó hiển thị trên cùng phần nền trắng có chữ á thử xóa đi xem

2024-08-16 08:06 UTC, huongnt-2545 commented on wibu_catalog/templates/html/warehouse.html
> +        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-..." crossorigin="anonymous">
tải source về đặt static nha

2024-08-16 08:06 UTC, huongnt-2545 commented on wibu_catalog/templates/html/warehouse.html
> +    <script src="{% static 'homepage.js' %}"></script>
cho lên thẻ `<head>` đi e

2024-08-16 08:06 UTC, huongnt-2545 commented on wibu_catalog/templates/html/warehouse.html
> +        <h1 style="color: brown;">
`style="color: brown;"` -> move vào file internal css, check tương tự trong file nhé

2024-08-16 08:06 UTC, huongnt-2545 commented on wibu_catalog/templates/html/warehouse.html
> +                        <li><a href="#">{% trans "Kids" %}</a></li>
thông tin genre có lưu trong DB ko e?

2024-08-16 08:06 UTC, huongnt-2545 commented on wibu_catalog/templates/html/warehouse.html
> +                                    <span class="episode">{% trans "Episode 260" %}</span>
data fake thì để 1 vài cái hiển thị để test thôi, còn đâu xóa đi e

2024-08-16 08:06 UTC, huongnt-2545 commented on wibu_catalog/views.py
> +    products = Product.objects.all()
thêm xử lý phân trang

2024-08-16 08:13 UTC, hoanghaiphongg commented on wibu_catalog/templates/html/warehouse.html
> +                        <li><a href="#">{% trans "Kids" %}</a></li>
có thưa chị

2024-08-19 03:59 UTC, hoanghaiphongg commented
Ready

2024-08-19 04:08 UTC, dolinhchi approved these changes

2024-08-19 08:45 UTC, huongnt-2545 approved these changes
C có cmt nhỏ, e fix ở pull sau nhé
Pull này merge nha

2024-08-19 08:45 UTC, huongnt-2545 commented on wibu_catalog/views.py
> +    paginator = Paginator(products_list, 12)
`12` -> cho vào file constants e nhé

2024-08-19 08:45 UTC, merged