Done doi mk
awesome-academy/python-naitei2024_my-wibu-list pull request #24
Opened 2024-08-26 04:10 UTC by hoanghaiphongg

## Checklist tự review pull trước khi ready để trainer review
- [ ] Sử dụng thụt lề 2 spaces/4 spaces đồng nhất ở tất cả các files (setting lại vscode /sublime text/ ... nếu chưa cài đặt)
- [ ] Cuối mỗi file kiểm tra có end line (khi đẩy lên git xem file change không bị lỗi tròn đỏ ở cuối file)
- [ ] Mỗi dòng nếu quá dài, cần xuống dòng (maximum: 80 kí tự mỗi dòng, setting trong IDE)
- [ ] Tham khảo Python coding convention https://peps.python.org/pep-0008/
- [ ] Kiểm tra mỗi pull request chỉ 1 commit, nếu nhiều hơn 1 commit thì hãy gộp commit thành 1 rồi đẩy lại lên git
- [ ] Install [PEP8](https://pypi.org/project/pep8/) ở local để check và fix các lỗi liên quan đến syntax, coding convention. Khi gửi thì chụp ảnh PASS đính kèm trong pull
- [ ] Nếu làm việc nhóm trong project thì mỗi pull cần ít nhất 1 APPROVED từ thành viên trong nhóm

## Related Tickets
- ticket [#792728](https://edu-redmine.sun-asterisk.vn/issues/79278)

## WHAT (optional)
- Change number items `completed/total` in admin page.

## HOW
- I edit js file, inject not_vary_normal items in calculate function.

## WHY (optional)
- Because in previous version - number just depends on `normal` items. But in new version, we have `state` and `confirm_state` depends on both `normal` + `not_normal` items.

## Evidence (Screenshot or Video)

## Notes (Kiến thức tìm hiểu thêm)

2024-08-27 08:05 UTC, thanhtb-0507 requested changes
Có một số chỗ cần sửa như sau:

2024-08-27 08:05 UTC, thanhtb-0507 commented on wibu_catalog/forms.py
> +
Cái này chắc chắn chưa chạy pep8 hoặc pycodestyle, tải về chạy và sửa theo nhá Phong ơi.

2024-08-27 08:05 UTC, thanhtb-0507 commented on wibu_catalog/forms.py
> +        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': _('New Password')}),
Dòng này 103 ký tự, tải pycodestyle về chạy nhé.

2024-08-27 08:05 UTC, thanhtb-0507 commented on wibu_catalog/templates/html/change_password.html
> +<!DOCTYPE html>
File này là html mà đang thụt dòng 4 space, xem lại nhé.

2024-08-27 08:05 UTC, thanhtb-0507 commented on wibu_catalog/urls.py
> +    #url for change password view
Cách 1 dòng cho dễ đọc

2024-08-27 08:05 UTC, thanhtb-0507 commented on wibu_catalog/urls.py
> +    path('change-password/', views.ChangePassword.as_view(), name='change_password'),
Quá 80 ký tự 1 dòng!

2024-08-27 08:24 UTC, hoanghaiphongg commented
Ready

2024-08-28 01:13 UTC, thanhtb-0507 requested changes

2024-08-28 01:13 UTC, thanhtb-0507 commented on wibu_catalog/forms.py
> +
Chỗ này vẫn chưa thấy sửa nhá, thêm 1 dòng enter Phong ơi.

2024-08-28 01:13 UTC, thanhtb-0507 commented on wibu_catalog/forms.py
> +
Also chạy pycodestyle đi

2024-08-28 01:13 UTC, thanhtb-0507 commented on wibu_catalog/models.py
> +import uuid
import này cho lên đầu nhé.
Thứ tự của các import sẽ là 

1.    thư viện chuẩn
2.    django stuff
3.    thư viện bên thứ 3 (vd: Cloundinary)
4.    import từ các file mình tạo.

Sửa lại nó sẽ như thế này, Phong kiểm tra xem đủ chưa thì bổ sung không thì dùng luôn nhá.:
```
import uuid
from django.contrib.auth.hashers import check_password, make_password
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from cloudinary.models import CloudinaryField
```

2024-08-28 01:13 UTC, thanhtb-0507 commented on wibu_catalog/views.py
> +from django.contrib.auth.hashers import check_password,make_password
Thiếu space sau dấu phẩy

2024-08-28 01:13 UTC, thanhtb-0507 commented on wibu_catalog/views.py
> +        new_password_confirmation = request.POST.get('new_password_confirmation')
dòng này có thể cắt như sau để đảm bảo luật 80 ký tự 1 dòng:
```python
        new_password_confirmation = request.POST.\
            get('new_password_confirmation')
```

2024-08-28 01:13 UTC, thanhtb-0507 commented on wibu_catalog/models.py
> +import uuid
also kiểm tra lại dòng 344 (cần cách thêm 1 dòng) và 734 (khoảng trắng cuối trang)

2024-08-28 01:52 UTC, thanhtb-0507 commented
Hiện tại tôi đã clone về và chạy thử, không những không thay đổi gì về mật khẩu ở wibu_catalog_users table mà còn không đăng nhập được nữa nhé. Cả uid 8, 9, 10, 11 đăng nhập đều không được.
Sau khi người dùng đổi mk xong, Phong có thể đưa một cái message hoặc sang một trang html khác ghi đổi mật khẩu thành công kèm thêm một nút về trang chủ hoặc đăng nhập được không? Tại đổi mật khẩu xong vẫn đứng ở trang đổi mật khẩu á.

2024-08-28 02:04 UTC, hoanghaiphongg commented
> Hiện tại tôi đã clone về và chạy thử, không những không thay đổi gì về mật khẩu ở wibu_catalog_users table mà còn không đăng nhập được nữa nhé. Cả uid 8, 9, 10, 11 đăng nhập đều không được. Sau khi người dùng đổi mk xong, Phong có thể đưa một cái message hoặc sang một trang html khác ghi đổi mật khẩu thành công kèm thêm một nút về trang chủ hoặc đăng nhập được không? Tại đổi mật khẩu xong vẫn đứng ở trang đổi mật khẩu á.



Tại vì logic đã được sửa để phù hợp với mật khẩu được mã hóa, téo tôi sẽ up bản export dữ liệu lên nhóm để mọi người cùng đăng nhập và đổi mk được

2024-08-28 03:24 UTC, DQB-201103 approved these changes

2024-08-28 03:54 UTC, hoanghaiphongg commented
Ready

2024-08-28 04:42 UTC, thanhtb-0507 approved these changes

2024-08-28 06:27 UTC, huongnt-2545 commented on wibu_catalog/models.py
> +from django.contrib.auth.hashers import check_password
gộp 1 dòng import đc nè e
```suggestion
from django.contrib.auth.hashers import make_password, check_password
```

2024-08-28 06:27 UTC, huongnt-2545 commented on wibu_catalog/models.py
> +from django.urls import reverse
dư thừa code (đã có ở dòng số 5)

2024-08-28 06:27 UTC, huongnt-2545 commented on wibu_catalog/models.py
> +            return False
```suggestion
        return check_password(user_input_password, hashed_password)
```

2024-08-28 07:05 UTC, hoanghaiphongg commented
Ready

2024-08-28 07:07 UTC, thanhtb-0507 approved these changes

2024-08-28 08:47 UTC, huongnt-2545 approved these changes

2024-08-28 08:47 UTC, merged