Sửa chức năng lọc sản phẩm và đăng ký người dùng + Unit Test
awesome-academy/python-naitei2024_my-wibu-list pull request #26
Opened 2024-08-27 16:50 UTC by hoanghaiphongg

## Checklist tự review pull trước khi ready để trainer review

-   [x] Sử dụng thụt lề 2 spaces/4 spaces đồng nhất ở tất cả các files (setting lại vscode /sublime text/ ... nếu chưa cài đặt)
-   [x] Cuối mỗi file kiểm tra có end line (khi đẩy lên git xem file change không bị lỗi tròn đỏ ở cuối file)
-   [x] Mỗi dòng nếu quá dài, cần xuống dòng (maximum: 80 kí tự mỗi dòng, setting trong IDE)
-   [x] Tham khảo Python coding convention https://peps.python.org/pep-0008/
-   [x] Kiểm tra mỗi pull request chỉ 1 commit, nếu nhiều hơn 1 commit thì hãy gộp commit thành 1 rồi đẩy lại lên git
-   [x] Install [PEP8](https://pypi.org/project/pep8/) ở local để check và fix các lỗi liên quan đến syntax, coding convention. Khi gửi thì chụp ảnh PASS đính kèm trong pull
-   [ ] Nếu làm việc nhóm trong project thì mỗi pull cần ít nhất 1 APPROVED từ thành viên trong nhóm

## Related Tickets

-   ticket redmine [80331](https://edu-redmine.sun-asterisk.vn/issues/80331) [80218](https://edu-redmine.sun-asterisk.vn/issues/80218), [80221](https://edu-redmine.sun-asterisk.vn/issues/80221), [80222](https://edu-redmine.sun-asterisk.vn/issues/80222), [80223](https://edu-redmine.sun-asterisk.vn/issues/80223)

## WHAT (optional)

-   Fix lại lỗi chuyển trang nhưng không áp dụng bộ lọc 

## HOW

-   I edit js file, inject not_vary_normal items in calculate function.

## WHY (optional)

-   Because in previous version - number just depends on `normal` items. But in new version, we have `state` and `confirm_state` depends on both `normal` + `not_normal` items.

## Evidence (Screenshot or Video)
- Pass pycodestyle :
![image](https://github.com/user-attachments/assets/14064c2c-3996-487e-8018-e6887ddc7ac6)
- Product filter unit test:
![image](https://github.com/user-attachments/assets/1ea3e50b-39d0-44f0-8aa6-2a801ffa7d82)
-  Register Unit test :
![image](https://github.com/user-attachments/assets/3c84e050-e27d-4dd1-940d-48236c479490)
- Chỉnh sửa bộ lọc sản phẩm : 

https://github.com/user-attachments/assets/8e840f20-86c6-4528-96a2-1365bfcd096b

- Chỉnh sửa chức năng đăng ký tài khoản người dùng mới:

https://github.com/user-attachments/assets/ef959abc-3eb5-4b15-98ce-bb28c8372dec

## Notes (Kiến thức tìm hiểu thêm)

2024-08-28 02:04 UTC, thanhtb-0507 requested changes
Tôi nghĩ cái pull này nên được để chị review trước, tất nhiên là sau khi Phong check lại mấy cái pep8 bằng pycodestyle rồi.
Về phần filter thì khá ổn rồi, nhưng nếu không muốn filter nữa thì thế nào? Cần phải có một nút bỏ filter không (về cơ bản là clone lại cái nút product ở header).

Hiện sản phẩm đang được hiển thị theo 4x3, mà chỉ hiện có 10 sản phẩm nên đang bị 2 ô trống nhé, cái này là ý kiến cá nhân của tôi nên bỏ qua cũng được.
![image](https://github.com/user-attachments/assets/4f6b2170-ba15-46c6-8010-b19165ce6990)

Lướt xuống cuối trang có phần RECOMENDS đấy, nếu làm được nó hoạt động thì tốt còn không thì xoá ngay và luôn không là bị hỏi đó!

2024-08-28 02:04 UTC, thanhtb-0507 commented on wibu_catalog/forms.py
> +
Vẫn là cách 2 dòng chứ không phải 1 dòng nhé, 
pycodestyle đê pycodestyle đê pycodestyle đê pycodestyle đê

2024-08-28 02:04 UTC, thanhtb-0507 commented on wibu_catalog/models.py
> +import uuid
trong một pull nào đấy tôi có nhắc Phong sửa thì sửa theo nhé

2024-08-29 07:55 UTC, thanhtb-0507 approved these changes

2024-08-29 08:55 UTC, hoanghaiphongg commented
Ready

2024-08-30 02:35 UTC, hoanghaiphongg commented
READYYYYYYYYY

2024-08-30 02:49 UTC, huongnt-2545 approved these changes

2024-08-30 02:49 UTC, merged